"use client";

import { useState } from "react";
import { Eye, Clock, LayoutGrid, Users, Megaphone, Target, AlertTriangle, FileText } from "lucide-react";
import { PageHeader } from "@/components/layout/PageHeader";
import { Card } from "@/components/ui/Card";
import { Button } from "@/components/ui/Button";
import { reportTypes } from "@/lib/mock-data";
import { cn } from "@/lib/utils";

const reportIcon: Record<string, typeof LayoutGrid> = {
  "founder-weekly": LayoutGrid,
  "telecaller-scorecard": Users,
  "campaign-roi": Megaphone,
  "lead-quality-audit": Target,
  "leakage-report": AlertTriangle,
  custom: FileText,
};

const previewSections = [
  "Executive Summary (₹ KPIs)",
  "Revenue Trend Chart",
  "Team Health Snapshot",
  "Top 3 AI Insights",
  "Leakage Summary",
];

export default function ReportGeneratorPage() {
  const [selected, setSelected] = useState("founder-weekly");
  const selectedReport = reportTypes.find((r) => r.key === selected)!;

  return (
    <div className="pb-10">
      <PageHeader title="AI Report Generator" description="Auto-generate reports on any timeframe — scheduled or on demand" />

      <div className="mt-4 grid grid-cols-1 gap-4 px-4 sm:px-6 lg:px-8 lg:grid-cols-2">
        <div className="space-y-4">
          <Card className="p-5">
            <h3 className="flex items-center gap-2 text-sm font-semibold text-slate-900">
              <FileText className="size-4" /> Report Type
            </h3>
            <div className="mt-3 space-y-2">
              {reportTypes.map((r) => {
                const Icon = reportIcon[r.key];
                return (
                  <button
                    key={r.key}
                    onClick={() => setSelected(r.key)}
                    className={cn(
                      "flex w-full items-center gap-3 rounded-xl border px-4 py-3 text-left transition-colors",
                      selected === r.key ? "border-primary-500 bg-primary-50" : "border-transparent bg-slate-50 hover:bg-slate-100"
                    )}
                  >
                    <span className="flex size-8 items-center justify-center rounded-lg bg-white text-slate-500">
                      <Icon className="size-4" />
                    </span>
                    <span>
                      <span className={cn("block text-sm font-semibold", selected === r.key ? "text-primary-700" : "text-slate-900")}>
                        {r.name}
                      </span>
                      <span className="block text-xs text-slate-500">{r.description}</span>
                    </span>
                  </button>
                );
              })}
            </div>
          </Card>

          <Card className="p-5">
            <h3 className="flex items-center gap-2 text-sm font-semibold text-slate-900">⚙ Configuration</h3>
            <div className="mt-3 space-y-4">
              <div>
                <label className="mb-1.5 block text-xs font-semibold uppercase tracking-wide text-slate-500">Date Range</label>
                <input defaultValue="This month" className="input" />
              </div>
              <div>
                <label className="mb-1.5 block text-xs font-semibold uppercase tracking-wide text-slate-500">Recipients</label>
                <input defaultValue="rohit@prestateadvisory.in" className="input" />
              </div>
              <div>
                <label className="mb-1.5 block text-xs font-semibold uppercase tracking-wide text-slate-500">Format</label>
                <input defaultValue="PDF · A4" className="input" />
              </div>
              <label className="flex items-center justify-between rounded-lg bg-slate-50 px-3 py-2.5">
                <span className="text-sm text-slate-700">Every Monday 9:00 AM — email delivery</span>
                <span className="relative inline-flex h-5 w-9 items-center rounded-full bg-primary-600">
                  <span className="absolute right-0.5 size-4 rounded-full bg-white" />
                </span>
              </label>
            </div>
          </Card>
        </div>

        <Card className="p-5">
          <div className="flex items-center justify-between">
            <h3 className="flex items-center gap-2 text-sm font-semibold text-slate-900">
              <Eye className="size-4" /> Report Preview
            </h3>
            <Button size="sm">Generate Preview</Button>
          </div>

          <div className="mt-4 rounded-xl bg-slate-50 p-4">
            <p className="font-semibold text-slate-900">{selectedReport.name}</p>
            <p className="text-xs text-slate-400">Prestige Estates Advisory · June 2026 · Generated by LeadPilot AI</p>
          </div>

          <div className="mt-3 space-y-3">
            {previewSections.map((s) => (
              <div key={s} className="flex items-center gap-2 text-sm text-slate-300">
                <Clock className="size-4" />
                {s}
              </div>
            ))}
          </div>
        </Card>
      </div>
    </div>
  );
}
